import { describe, expect, it, vi } from "vitest";
import { ExportService } from "./export.service.js";
import { ImportService } from "./import.service.js";
import { mkdir, mkdtemp, readFile, writeFile } from "node:fs/promises";
import { tmpdir } from "node:os";
import { join } from "node:path";
import { createZip } from "./zip.js";

describe("ImportService", () => {
  it("validates an archive generated by ExportService", async () => {
    const root = await mkdtemp(join(tmpdir(), "promptvault-import-"));
    const prisma = { prompt: { findMany: async () => [] }, model: { findMany: async () => [] }, promptTemplate: { findMany: async () => [] }, promptSkill: { findMany: async () => [] }, personalRule: { findMany: async () => [] }, category: { findMany: async () => [] }, tag: { findMany: async () => [] }, compilationRun: { findMany: async () => [] } };
    const archive = await new ExportService(prisma as never, join(root, "storage"), join(root, "exports")).createExport();
    expect(new ImportService().validate(await readFile(archive.path))).toMatchObject({ valid: true, schemaVersion: 1, promptCount: 0, assetCount: 0 });
  });

  it("rejects malformed archives", () => {
    expect(() => new ImportService().validate(Buffer.from("not a zip"))).toThrow("IMPORT_INVALID_ZIP");
  });

  it("rejects payload entries omitted from the manifest", () => {
    const json = (value: unknown) => Buffer.from(JSON.stringify(value));
    const archive = createZip([
      { name: "manifest.json", data: json({ schemaVersion: 1, promptCount: 0, entries: [] }) },
      { name: "prompts.json", data: json([]) },
      { name: "knowledge.json", data: json({ models: [], templates: [], skills: [], personalRules: [], categories: [], tags: [] }) },
    ]);
    expect(() => new ImportService().validate(archive)).toThrow("IMPORT_MANIFEST_INCOMPLETE");
  });

  it("previews prompt conflicts without writing", async () => {
    const root = await mkdtemp(join(tmpdir(), "promptvault-import-preview-"));
    const source = exportPrisma([{ id: "prompt-1", title: "Existing title" }]);
    const archive = await new ExportService(source as never, join(root, "source"), join(root, "exports")).createExport();
    const target = restorePrisma(["prompt-1"]);

    const result = await new ImportService(target as never, join(root, "target")).preview(await readFile(archive.path));

    expect(result).toMatchObject({ promptCount: 1, assetCount: 0, conflicts: ["prompt-1"], missingAssets: [] });
    expect(target.$transaction).not.toHaveBeenCalled();
  });

  it("merges prompts and their versions by stable ids", async () => {
    const root = await mkdtemp(join(tmpdir(), "promptvault-import-merge-"));
    const source = exportPrisma([{ id: "prompt-2", title: "Imported title", versions: [{ id: "version-1", promptId: "prompt-2", version: 1, snapshot: { contentZh: "内容" } }] }]);
    const archive = await new ExportService(source as never, join(root, "source"), join(root, "exports")).createExport();
    const target = restorePrisma([]);

    const result = await new ImportService(target as never, join(root, "target")).restore(await readFile(archive.path), "MERGE");

    expect(result).toMatchObject({ mode: "MERGE", promptCount: 1, restoredAssets: 0 });
    expect(target.tx.prompt.upsert).toHaveBeenCalledWith(expect.objectContaining({ where: { id: "prompt-2" } }));
    expect(target.tx.promptVersion.upsert).toHaveBeenCalledWith(expect.objectContaining({ where: { id: "version-1" } }));
  });

  it("does not overwrite a conflicting local Prompt in merge mode", async () => {
    const root = await mkdtemp(join(tmpdir(), "promptvault-import-conflict-"));
    const source = exportPrisma([{ id: "prompt-1", title: "Old backup" }]);
    const archive = await new ExportService(source as never, join(root, "source"), join(root, "exports")).createExport();
    const target = restorePrisma(["prompt-1"]);
    await new ImportService(target as never, join(root, "target")).restore(await readFile(archive.path), "MERGE");
    expect(target.tx.prompt.upsert).not.toHaveBeenCalled();
    expect(target.tx.promptVersion.deleteMany).not.toHaveBeenCalled();
  });

  it("fails closed before replace when the automatic backup fails", async () => {
    const root = await mkdtemp(join(tmpdir(), "promptvault-import-replace-"));
    const source = exportPrisma([]);
    const archive = await new ExportService(source as never, join(root, "source"), join(root, "exports")).createExport();
    const target = restorePrisma([]);
    const backup = { createExport: vi.fn().mockRejectedValue(new Error("disk full")) };

    await expect(new ImportService(target as never, join(root, "target"), backup as never).restore(await readFile(archive.path), "REPLACE"))
      .rejects.toThrow("IMPORT_PRE_BACKUP_FAILED");
    expect(target.$transaction).not.toHaveBeenCalled();
  });

  it("restores overwritten asset files when the database transaction fails", async () => {
    const root = await mkdtemp(join(tmpdir(), "promptvault-import-rollback-"));
    const asset = { id: "asset-1", promptId: "prompt-3", role: "COVER", storageKey: "prompt-3/cover.png", mimeType: "image/png", originalName: "cover.png", byteSize: 3, checksum: "checksum", createdAt: new Date(), width: null, height: null };
    const sourceRoot = join(root, "source");
    const targetRoot = join(root, "target");
    await mkdir(join(sourceRoot, "prompt-3"), { recursive: true });
    await mkdir(join(targetRoot, "prompt-3"), { recursive: true });
    await writeFile(join(sourceRoot, asset.storageKey), "new");
    await writeFile(join(targetRoot, asset.storageKey), "old");
    const source = exportPrisma([{ id: "prompt-3", title: "Imported", assets: [asset] }]);
    const archive = await new ExportService(source as never, sourceRoot, join(root, "exports")).createExport();
    const target = restorePrisma([]);
    target.$transaction.mockImplementationOnce(async (callback: (client: typeof target.tx) => unknown) => { await callback(target.tx); throw new Error("commit failed"); });

    await expect(new ImportService(target as never, targetRoot).restore(await readFile(archive.path), "MERGE")).rejects.toThrow("commit failed");
    expect(await readFile(join(targetRoot, asset.storageKey), "utf8")).toBe("old");
  });
});

function exportPrisma(promptInputs: Array<{ id: string; title: string; versions?: unknown[]; assets?: unknown[] }>) {
  const prompts = promptInputs.map((prompt) => ({
    description: null, contentZh: "内容", contentEn: "Content", negativeZh: null, negativeEn: null,
    status: "EXPERIMENT", rating: 0, origin: "MANUAL", modelTaskId: "task-1", categoryId: null,
    compilationRunId: null, createdAt: new Date(), updatedAt: new Date(), tags: [], assets: prompt.assets ?? [], versions: prompt.versions ?? [],
    ...prompt,
  }));
  return {
    prompt: { findMany: vi.fn(async () => prompts) }, model: { findMany: vi.fn(async () => []) },
    promptTemplate: { findMany: vi.fn(async () => []) }, promptSkill: { findMany: vi.fn(async () => []) },
    personalRule: { findMany: vi.fn(async () => []) }, category: { findMany: vi.fn(async () => []) }, tag: { findMany: vi.fn(async () => []) }, compilationRun: { findMany: vi.fn(async () => []) },
  };
}

function restorePrisma(existingPromptIds: string[]) {
  const tx = {
    promptVersion: { deleteMany: vi.fn(), upsert: vi.fn() }, promptTag: { deleteMany: vi.fn(), createMany: vi.fn() },
    asset: { deleteMany: vi.fn(), upsert: vi.fn() }, prompt: { deleteMany: vi.fn(), upsert: vi.fn() },
    compilationSkill: { deleteMany: vi.fn() }, compilationRun: { deleteMany: vi.fn() }, templateSkill: { deleteMany: vi.fn() },
    skillModelTask: { deleteMany: vi.fn(), createMany: vi.fn() }, personalRule: { deleteMany: vi.fn(), upsert: vi.fn() },
    promptTemplate: { deleteMany: vi.fn(), upsert: vi.fn() }, promptSkill: { deleteMany: vi.fn(), upsert: vi.fn() },
    modelTask: { deleteMany: vi.fn(), upsert: vi.fn() }, model: { deleteMany: vi.fn(), upsert: vi.fn() },
    tag: { deleteMany: vi.fn(), upsert: vi.fn() }, category: { deleteMany: vi.fn(), upsert: vi.fn() },
  };
  return {
    tx,
    prompt: { findMany: vi.fn(async () => existingPromptIds.map((id) => ({ id }))) },
    $transaction: vi.fn(async (callback: (client: typeof tx) => unknown) => callback(tx)),
  };
}
