import { describe, expect, it } from "vitest";
import { ExportService } from "./export.service.js";
import { ImportService } from "./import.service.js";
import { mkdtemp, readFile } from "node:fs/promises";
import { tmpdir } from "node:os";
import { join } from "node:path";

describe("ImportService", () => {
  it("validates an archive generated by ExportService", async () => {
    const root = await mkdtemp(join(tmpdir(), "promptvault-import-"));
    const prisma = { prompt: { findMany: async () => [] }, model: { findMany: async () => [] }, promptTemplate: { findMany: async () => [] }, promptSkill: { findMany: async () => [] }, personalRule: { findMany: async () => [] }, category: { findMany: async () => [] }, tag: { findMany: async () => [] } };
    const archive = await new ExportService(prisma as never, join(root, "storage"), join(root, "exports")).createExport();
    expect(new ImportService().validate(await readFile(archive.path))).toMatchObject({ valid: true, schemaVersion: 1, promptCount: 0, assetCount: 0 });
  });

  it("rejects malformed archives", () => {
    expect(() => new ImportService().validate(Buffer.from("not a zip"))).toThrow("IMPORT_INVALID_ZIP");
  });
});
