import type { KnowledgeRecord } from "../domain/types";

const updatedAt = "2026-08-12T00:00:00.000Z";

export const BUILT_IN_KNOWLEDGE: readonly KnowledgeRecord[] = [
  {
    id: "builtin-template-general",
    stableKey: "template.general",
    kind: "TEMPLATE",
    owner: "BUILT_IN",
    nameZh: "通用设计提示词",
    nameEn: "General design prompt",
    contentZh: "任务要求：{{requirement}}",
    contentEn: "Task requirement: {{requirement}}",
    enabled: true,
    version: 1,
    priority: 0,
    category: "general",
    updatedAt,
  },
  {
    id: "builtin-skill-spatial",
    stableKey: "skill.spatial-consistency",
    kind: "SKILL",
    owner: "BUILT_IN",
    nameZh: "空间一致性",
    nameEn: "Spatial consistency",
    contentZh: "保持原始空间结构、主体比例与关键构件关系准确。",
    contentEn: "Preserve the original spatial structure, subject proportions, and relationships between key elements.",
    enabled: true,
    version: 1,
    priority: 20,
    category: "constraints",
    updatedAt,
  },
  {
    id: "builtin-skill-material",
    stableKey: "skill.material-detail",
    kind: "SKILL",
    owner: "BUILT_IN",
    nameZh: "材质细节",
    nameEn: "Material detail",
    contentZh: "清楚描述主要材质、表面工艺、连接方式与光线下的质感。",
    contentEn: "Clearly describe primary materials, surface finishes, connections, and their appearance under the intended lighting.",
    enabled: true,
    version: 1,
    priority: 10,
    category: "detail",
    updatedAt,
  },
  {
    id: "builtin-rule-output",
    stableKey: "rule.clear-output",
    kind: "RULE",
    owner: "BUILT_IN",
    nameZh: "清晰可执行",
    nameEn: "Clear and actionable",
    contentZh: "表达应具体、无歧义，并避免互相冲突的要求。",
    contentEn: "Keep the instructions specific, unambiguous, and free from conflicting requirements.",
    enabled: true,
    version: 1,
    priority: 10,
    category: "constraints",
    updatedAt,
  },
];
